<a href="https://colab.research.google.com/github/Sanjai-R-Data/Python_Mastery/blob/main/NumPy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NumPy
# NumPy stands for Numerical Python
# NumPy is a Python library used for working with arrays.
# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# use of NumPy:
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# the array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
# Arrays are very frequently used in data science, where speed and resources are very important.

# why NumPy are faster?
# NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

# The source code for NumPy is located at this github repository https://github.com/numpy/numpy

In [6]:
import numpy as np

myarr = np.array([1,2,3,4,5])
print(myarr)

myarr2 = np.array((6,7,8,9,10))
print(myarr2)

print(type(myarr))
print(type(myarr2))

[1 2 3 4 5]
[ 6  7  8  9 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [2]:
# checking numpy version

import numpy as np

print(np.__version__)

2.0.2


In [11]:
# dimensions in array
# 0D - Array:

import numpy as np
myarr = np.array(30)
print(myarr)

# 1D - Array:
myarr2 = np.array([1,2,3,4,5])
print(myarr2)

# 2D - Array:
myarr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(myarr3)

# 3D - Array:
myarr4 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(myarr4)
# check the number of dimensions (ndim):
print(myarr.ndim)
print(myarr2.ndim)
print(myarr3.ndim)
print(myarr4.ndim)

30
[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
0
1
2
3


In [12]:
# higher dimensional arrays:
import numpy as np
myarr = np.array([1,2,3,4,5], ndmin=6)
print(myarr)

[[[[[[1 2 3 4 5]]]]]]


In [21]:
# accessing arrays using index:
import numpy as np
myarr = np.array([1,2,3,4,5])
print(myarr[0])
print(myarr[1])
print(myarr[2])
print(myarr[3])
print(myarr[4])

# accessing 2D arrays:
myarr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(myarr2[0,2])
print(myarr2[1,2])

# accessing 3D arrays:
myarr3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(myarr3[0,1,2])
print(myarr3[1,1,2])

# negative indexing:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, -1])


1
2
3
4
5
3
8
8
18
10


In [29]:
# slicing in arrays(numpy)

import numpy as np
myarr = np.array([1, 2, 3, 4, 5, 6, 7])
print(myarr[1:5])

myarr2 = np.array([1, 2, 3, 4, 5, 6, 7])
print(myarr2[4:])

myarr2 = np.array([1, 2, 3, 4, 5, 6, 7])
print(myarr2[:4])

myarr3 = np.array([1, 2, 3, 4, 5, 6, 7])
print(myarr3[1:5:2])# with step value

myarr4 = np.array([1, 2, 3, 4, 5, 6, 7])
print(myarr4[-3:-1])

# in multidimensional array:
myarr5 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

myarr6 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(myarr6[0:2, 2])

myarr7 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(myarr7[0:2, 1:4])



[2 3 4 5]
[5 6 7]
[1 2 3 4]
[2 4]
[5 6]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
