<a href="https://colab.research.google.com/github/Sanjai-R-Data/Python_Mastery/blob/main/NumPy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NumPy
# NumPy stands for Numerical Python
# NumPy is a Python library used for working with arrays.
# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# use of NumPy:
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# the array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
# Arrays are very frequently used in data science, where speed and resources are very important.

# why NumPy are faster?
# NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

# The source code for NumPy is located at this github repository https://github.com/numpy/numpy

In [ ]:
import numpy as np

myarr = np.array([1,2,3,4,5])
print(myarr)

myarr2 = np.array((6,7,8,9,10))
print(myarr2)

print(type(myarr))
print(type(myarr2))

[1 2 3 4 5]
[ 6  7  8  9 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# checking numpy version

import numpy as np

print(np.__version__)

2.0.2


In [ ]:
# dimensions in array
# 0D - Array:

import numpy as np
myarr = np.array(30)
print(myarr)

# 1D - Array:
myarr2 = np.array([1,2,3,4,5])
print(myarr2)

# 2D - Array:
myarr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(myarr3)

# 3D - Array:
myarr4 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(myarr4)
# check the number of dimensions (ndim):
print(myarr.ndim)
print(myarr2.ndim)
print(myarr3.ndim)
print(myarr4.ndim)

30
[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
0
1
2
3


In [ ]:
# higher dimensional arrays:
import numpy as np
myarr = np.array([1,2,3,4,5], ndmin=6)
print(myarr)

[[[[[[1 2 3 4 5]]]]]]


In [ ]:
# accessing arrays using index:
import numpy as np
myarr = np.array([1,2,3,4,5])
print(myarr[0])
print(myarr[1])
print(myarr[2])
print(myarr[3])
print(myarr[4])

# accessing 2D arrays:
myarr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(myarr2[0,2])
print(myarr2[1,2])

# accessing 3D arrays:
myarr3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(myarr3[0,1,2])
print(myarr3[1,1,2])

# negative indexing:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, -1])


1
2
3
4
5
3
8
8
18
10


In [ ]:
# slicing in arrays(numpy)

import numpy as np
myarr = np.array([1, 2, 3, 4, 5, 6, 7])
print(myarr[1:5])

myarr2 = np.array([1, 2, 3, 4, 5, 6, 7])
print(myarr2[4:])

myarr2 = np.array([1, 2, 3, 4, 5, 6, 7])
print(myarr2[:4])

myarr3 = np.array([1, 2, 3, 4, 5, 6, 7])
print(myarr3[1:5:2])# with step value

myarr4 = np.array([1, 2, 3, 4, 5, 6, 7])
print(myarr4[-3:-1])

# in multidimensional array:
myarr5 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

myarr6 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(myarr6[0:2, 2])

myarr7 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(myarr7[0:2, 1:4])



[2 3 4 5]
[5 6 7]
[1 2 3 4]
[2 4]
[5 6]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
# Data types in NumPy:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

In [ ]:
# we can check the data type of the array by using dtype:
import numpy as np
myarr = np.array([1,2,3,4,5])
print(myarr.dtype)

myarr2 = np.array(['apple', 'banana', 'cherry'])
print(myarr2.dtype)

# creating arrays with defined data types:
myarr3 = np.array([1,2,3,4,5], dtype='S')
print(myarr3.dtype)

# For i, u, f, S and U we can define size as well
myarr4 = np.array([1, 2, 3, 4], dtype='i4')
print(myarr4.dtype)

# ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect:
# myarr5 = np.array(['a', '2', '3'], dtype='i') is an example for it.


int64
<U6
|S1
int32


In [ ]:
# Converting Data Type on Existing Arrays:
# The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

import numpy as np
myarr = np.array([1.1, 2.1, 3.1])
newarr = myarr.astype('i') # can also use int or float too
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# The Difference Between Copy and View:
# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
# The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
# The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

import numpy as np
myarr = np.array([1, 2, 3, 4, 5])
x = myarr.copy() # no change as two seperate arrays
myarr[0] = 42
print(myarr)
print(x)

myarr2 = np.array([1, 2, 3, 4, 5])
y = myarr2.view() # changes
myarr2[0] = 42
print(myarr2)
print(y)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# Check if Array Owns its Data:
# Every NumPy array has the attribute base that returns None if the array owns the data.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) # copy owns data so it returns none
print(y.base) # view does not own data so it returns the original data

None
[1 2 3 4 5]


In [ ]:
# Shape of an Array:
# The shape of an array is the number of elements in each dimension
import numpy as np
myarr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(myarr.shape)

myarr2 = np.array([1, 2, 3, 4], ndmin=5)

print(myarr2)
print(myarr2.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [ ]:
# Reshaping arrays:
# Reshaping means changing the shape of an array.
# Reshaping means changing the shape of an array.
# By reshaping we can add or remove dimensions or change number of elements in each dimension.

import numpy as np
myarr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # converting 1D to 2D
newarr = myarr.reshape(4, 3)
print(newarr)

myarr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr2 = myarr2.reshape(2, 3, 2) # converting 1D to 3D
print(newarr2)

# we can reshape the arrays as long as the elements required for reshaping are equal in both shapes.
# We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Flattening the arrays:
# Flattening array means converting a multidimensional array into a 1D array.

import numpy as np
myarr = np.array([[1,2,3],[4,5,6]])
newarr = myarr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
# Iterating Arrays:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

# for 2d arrays:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr2:
  print(x)

arr3 = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr3:
  for y in x:
    print(y)

# for 3D arrays:
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr4:
  for y in x:
    for z in y:
      print(z)

1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Iterating Arrays Using nditer()
# The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
# Iterating Array With Different Data Types:
# We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
# NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

import numpy as np
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [ ]:
# Iterating With Different Step Size:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
# Enumerated Iteration Using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one.
# Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

import numpy as np
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

# for 2D arrays:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr2):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [15]:
# Joining NumPy Arrays:
# Joining means putting contents of two or more arrays in a single array.
# We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

import numpy as np
myarr1 = np.array([1, 2, 3])
myarr2 = np.array([4, 5, 6])
myarr3 = np.concatenate((myarr1, myarr2))
print(myarr3)

# join two 2D arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

# Joining Arrays Using Stack Functions:
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
# We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

arr3 = np.stack((arr1,arr2),axis = 1)
print(arr3)

# Stacking Along Rows:

arr4 = np.hstack((arr1,arr2))
print(arr4)

# Stacking Along columns:
arr5 = np.vstack((arr1,arr2))
print(arr5)

# Stacking Along Height (depth):
arr6 = np.dstack((arr1,arr2))
print(arr6)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [16]:
# Splitting NumPy Arrays:
# Splitting is reverse operation of Joining.
# We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
